# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/determinate-nix-action@v3
    - name: Install direnv with Nix
      uses: aldoborrero/direnv-nix-action@v2
      with:
        use_nix_profile: true
        nix_channel: nixpkgs
    - name: setup
      run: |
        cp .envrc.example .envrc
        direnv allow
        uv sync
    - name: Run flake8
      uses: suo/flake8-github-action@releases/v1
      if: success() | failure()
      with:
        checkName: 'build'   # NOTE: this needs to be the same as the job name
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Run mypy
      if: success() | failure()
      uses: sasanquaneuf/mypy-github-action@releases/v1
      with:
        checkName: 'build'   # NOTE: this needs to be the same as the job name
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Test with pytest
      if: success() | failure()
      run: |
        pytest -s -vvv
